# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU



#Contact page message sent email
#Gamil address
ACTION_MAILER_EMAIL_ADDRESS: "codetest1980@gmail.com"
#Gamil 2 段階認証プロセス password
ACTION_MAILER_EMAIL_PASSWORD: "lnbhibmwqlatlncx"


region:                ENV['AMAZON_S3_REGION'], 
aws_access_key_id:     ENV['AMAZON_ACCESS_KEY_ID'],
aws_secret_access_key: ENV['AMAZON_SECRET_ACCESS_KEY']

config.fog_directory:  ENV['AMAZON_S3_BUCKET_NAME']

